### ISSUE TITLE
Could not deserialize measurement 'jsonStr'

### ISSUE THREAD

**Issue by sdsantos** [ooni/probe-multiplatform#160]
Stacktrace:

```
 Could not deserialize measurement 'jsonStr' (Ask Gemini)
kotlinx.serialization.json.internal.JsonDecodingException: Encountered an unknown key 'header_name_diff'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
Current input: {"header_field_name":false,"header_field_number":false,"header_field_value":false,"header_name_capitalization":false,"header_name_diff":[],"request_line_capitalization":false,"total":false}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.UnknownKeyException(JsonExceptions.kt:78)
	at kotlinx.serialization.json.internal.JsonTreeDecoder.endStructure(TreeJsonDecoder.kt:283)
	at org.ooni.engine.models.TestKeys$TamperingKeys$$serializer.deserialize(TestKeys.kt:81)
	at org.ooni.engine.models.TestKeys$TamperingKeys$$serializer.deserialize(TestKeys.kt:81)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:26)
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:186)
	at org.ooni.engine.models.TamperingSerializer.deserialize(TestKeys.kt:130)
	at org.ooni.engine.models.TamperingSerializer.deserialize(TestKeys.kt:106)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
	at org.ooni.engine.models.TestKeys$$serializer.deserialize(TestKeys.kt:17)
	at org.ooni.engine.models.TestKeys$$serializer.deserialize(TestKeys.kt:17)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
	at org.ooni.engine.models.MeasurementResult$$serializer.deserialize(MeasurementResult.kt:8)
	at org.ooni.engine.models.MeasurementResult$$serializer.deserialize(MeasurementResult.kt:8)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.internal.NullableSerializer.deserialize(NullableSerializer.kt:30)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
	at org.ooni.engine.TaskEventMapper.invoke(TaskEventMapper.kt:191)
	at org.ooni.engine.Engine$startTask$1.invokeSuspend(Engine.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
```

**Comment by sdsantos** [comment]
Stacktrace:

```
 Could not deserialize measurement 'jsonStr' (Ask Gemini)
                                                                                                    kotlinx.serialization.json.internal.JsonDecodingException: Encountered an unknown key 'header_name_diff'.
                                                                                                    Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
                                                                                                    Current input: {"header_field_name":false,"header_field_number":false,"header_field_value":false,"header_name_capitalization":false,"header_name_diff":[],"request_line_capitalization":false,"total":false}
                                                                                                    	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
                                                                                                    	at kotlinx.serialization.json.internal.JsonExceptionsKt.UnknownKeyException(JsonExceptions.kt:78)
                                                                                                    	at kotlinx.serialization.json.internal.JsonTreeDecoder.endStructure(TreeJsonDecoder.kt:283)
                                                                                                    	at org.ooni.engine.models.TestKeys$TamperingKeys$$serializer.deserialize(TestKeys.kt:81)
                                                                                                    	at org.ooni.engine.models.TestKeys$TamperingKeys$$serializer.deserialize(TestKeys.kt:81)
                                                                                                    	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
                                                                                                    	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:26)
                                                                                                    	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:186)
                                                                                                    	at org.ooni.engine.models.TamperingSerializer.deserialize(TestKeys.kt:130)
                                                                                                    	at org.ooni.engine.models.TamperingSerializer.deserialize(TestKeys.kt:106)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
                                                                                                    	at org.ooni.engine.models.TestKeys$$serializer.deserialize(TestKeys.kt:17)
                                                                                                    	at org.ooni.engine.models.TestKeys$$serializer.deserialize(TestKeys.kt:17)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
                                                                                                    	at org.ooni.engine.models.MeasurementResult$$serializer.deserialize(MeasurementResult.kt:8)
                                                                                                    	at org.ooni.engine.models.MeasurementResult$$serializer.deserialize(MeasurementResult.kt:8)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.internal.NullableSerializer.deserialize(NullableSerializer.kt:30)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
                                                                                                    	at org.ooni.engine.TaskEventMapper.invoke(TaskEventMapper.kt:191)
                                                                                                    	at org.ooni.engine.Engine$startTask$1.invokeSuspend(Engine.kt:56)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
```
